Added color-hex-alpha rule
stylelint/stylelint pull request #4891
Opened 2020-08-08 18:22 UTC by ssivanatarajan

> Which issue, if any, is this issue related to?
Closes #4880
e.g. "Closes #000" or "None, as it's a documentation fix."

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self-explanatory."

2020-08-09 17:00 UTC, jeddy3 commented on lib/rules/color-hex-alpha/__tests__/index.js
> +testRule({
```suggestion
});

testRule({
```

2020-08-09 17:00 UTC, jeddy3 commented on lib/rules/color-hex-alpha/index.js
> +const ruleName = 'color-hex-alpha';
```suggestion
const valueParser = require('postcss-value-parser');

const ruleName = 'color-hex-alpha';
```

2020-08-09 17:02 UTC, jeddy3 commented on lib/rules/color-hex-alpha/index.js
> +			const parsedValue = valueParser(getValue(decl));
```suggestion
			const parsedValue = valueParser(decl.value));
```

`decl.value` will suffice as we're not changing the AST.

2020-08-09 17:02 UTC, jeddy3 commented on lib/rules/color-hex-alpha/index.js
> +
```suggestion
```

2020-08-09 17:08 UTC, jeddy3 commented on lib/rules/color-hex-alpha/__tests__/index.js
> +});
Let's get an additional `testRule` block with `syntax: "scss" and an interpolation accept test case, e.g.

```css
a { color: #{ff}; }
```

```js
testRule({
	ruleName,
	config: ["never"],
	syntax: 'scss',

	accept: [
		{
			code: 'a { color: #{ff}; }',
			description: 'scss interpolation',
		},
	],
});

2020-08-14 19:14 UTC, ssivanatarajan commented
@jeddy3 Made the changes Please review it.

2020-09-24 01:26 UTC, ssivanatarajan commented
@jeddy3 can u please review this PR

2020-10-29 05:15 UTC, ssivanatarajan commented
@jeddy3  any update on this ?

2020-12-22 06:19 UTC, ssivanatarajan commented
> @ssivanatarajan Thanks for the pull request. It's looking good.
> 
> I've requested some changes.
> 
> Can you also add the rule [to the list in the docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules/list.md), please?

added

2020-12-22 07:01 UTC, ssivanatarajan commented
@jeddy3 is anything that needs to be changed /reviewed?

2021-01-03 14:04 UTC, jeddy3 requested changes
Thanks for making the changes.

I've looked through the PR again and requested some more changes.

2021-05-29 08:23 UTC, jeddy3 commented
Finished in #5316

2021-05-29 08:23 UTC, closed without merging