Use postcss-value-parser for color-hex-length
stylelint/stylelint pull request #5106
Opened 2021-01-13 06:10 UTC by Dru89

`style-search` returns false positives when used with `css-in-js` object
notation. Continuing on the change made in #5101 (for issue #4826), this updates
`color-hex-length` to switch to using `postcss-value-parser`.

Unit tests have also been added to check the `css-in-js` syntax for this
rule.

2021-01-15 14:41 UTC, jeddy3 requested changes
@Dru89 Fantastic. Besides one minor request, this looks good to me right off the bat!

2021-01-15 14:41 UTC, jeddy3 commented on lib/rules/color-hex-length/index.js
> +	return decl;
```suggestion
```

We can remove this redundant return as per the other pull request.

At some point later down the line, we should refactor to move at least the `getValue` and `setValue` functions out to `/utils`. For now, let's duplicate them as you are doing, though.

2021-01-18 19:23 UTC, hudochenkov approved these changes
👍

2021-01-19 14:59 UTC, jeddy3 approved these changes

2021-01-19 15:04 UTC, merged

2021-01-19 15:04 UTC, jeddy3 commented
Changelog: 

> - Fixed: `color-hex-length` false negatives for css-in-js object notation ([#5106](https://github.com/stylelint/stylelint/pull/5106)).