WIP: feat(rules): add new rule declaration-block-no-duplicate-custom-prope…
stylelint/stylelint pull request #5125
Opened 2021-02-04 18:53 UTC by voskresla

> Which issue, if any, is this issue related to?

Closes #5124

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2021-02-04 21:07 UTC, voskresla commented
is it ok with CodeQL errors?

2021-02-05 11:49 UTC, jeddy3 requested changes
@voskresla Thanks, looking good!

I've requested some minor documentation changes.

> is it ok with CodeQL errors?

Yes. They're unrelated to this PR.

2021-02-05 11:49 UTC, jeddy3 commented on docs/user-guide/rules/list.md
> +- [`declaration-block-no-duplicate-custom-properties`](../../../lib/rules/declaration-block-no-duplicate-custom-properties/README.md): Disallow duplicate custom properties within declaration blocks.
Let's move this to the "Possible Errors -> Declaration Block" section (in alphabetical order).

I made a mistake in the blueprint, sorry.

2021-02-05 11:49 UTC, jeddy3 commented on lib/rules/declaration-block-no-duplicate-custom-properties/README.md
> +# declaration-block-no-duplicate-properties
```suggestion
# declaration-block-no-duplicate-custom-properties
```

2021-02-05 11:49 UTC, jeddy3 commented on lib/rules/declaration-block-no-duplicate-custom-properties/README.md
> +None
```suggestion
```

Let's remove as we don't normally have this title if there are no secondary options.

2021-02-05 11:49 UTC, jeddy3 commented on lib/rules/declaration-block-no-duplicate-custom-properties/__tests__/index.js
> +			code: 'a { color: var(--custom-property, --custom-property) }',
👍

2021-02-05 14:34 UTC, vankop approved these changes

2021-02-05 14:34 UTC, vankop commented on lib/rules/declaration-block-no-duplicate-custom-properties/index.js
> +			const decls = [];
better use `Set` for performance

2021-02-05 14:34 UTC, vankop commented on lib/rules/declaration-block-no-duplicate-custom-properties/index.js
> +					});
```suggestion
					});return;
```
don't need to add custom property again on line 51

2021-02-05 18:40 UTC, jeddy3 approved these changes
@voskresla Nicely done! LGTM.

2021-02-05 21:08 UTC, voskresla commented
big thx @vankop @jeddy3 for the perfect support.

2021-02-06 08:56 UTC, merged

2021-02-06 08:58 UTC, jeddy3 commented
Changelog entry added:

> - Added: `declaration-block-no-duplicate-custom-properties` rule ([#5125](https://github.com/stylelint/stylelint/pull/5125)).