Allow disable reporting to be controlled from the config file
stylelint/stylelint pull request #5126
Opened 2021-02-04 23:18 UTC by nex3

This will also make it easier to control disables on a file-by-file basis
once #3128 is implemented. It will also make it possible to add 
finer-grained configuration to these rules in the future.

2021-02-05 00:21 UTC, jathak approved these changes

2021-02-05 00:21 UTC, jathak commented on lib/needlessDisables.js
> +				// *any* rules, becuase it covers all of them.
```suggestion
				// *any* rules, because it covers all of them.
```

2021-02-05 12:18 UTC, vankop approved these changes

2021-02-05 12:47 UTC, jeddy3 requested changes
@nex3 Thank you. It's amazing to see this go in. As you said, it's the first step towards adding the `overrides` configuration property (which opens up so many possibilities). It's also the first step towards being able to [configure everything](https://github.com/stylelint/stylelint/issues/4843#issuecomment-650137005) from within the configuration object, rather than a hodgepodge of properties, parameters and flags.

I've requested some minor documentation changes.

At the start of last year we [restructured](https://github.com/stylelint/stylelint/pull/4548) and [rewrote](https://github.com/stylelint/stylelint/pull/4561) the majority of the docs. This included removing a lot of duplication where API parameters, CLI flags and configuration properties had fallen out of sync. 

I'm aware this pull request reintroduces duplication, but I suggest we roll with it for now. I'll also merge in https://github.com/stylelint/stylelint/pull/5005, which duplicates the CLI flags. Once everything is configurable within the configuration object, I think we'll be better positioned to revisit the documentation and find a structure that both avoids duplication and is intuitive for users.

2021-02-05 12:47 UTC, jeddy3 commented on docs/user-guide/configure.md
> +Ignore `styleline-disable` (e.g. `/* stylelint-disable block-no-empty */`) comments.
```suggestion
Ignore `stylelint-disable` (e.g. `/* stylelint-disable block-no-empty */`) comments.
```

2021-02-05 12:47 UTC, jeddy3 commented on docs/user-guide/configure.md
> +Emit errors for `stylelint-disable` comments that don't include actually match
```suggestion
Emit errors for `stylelint-disable` comments that don't match
```

2021-02-05 12:47 UTC, jeddy3 commented on docs/user-guide/configure.md
> +any lints that need to be disabled.
Let's remove the hard linebreak to be consistent with the rest of the file

2021-02-05 12:47 UTC, jeddy3 commented on docs/user-guide/configure.md
> +specified in the configuration object.
```suggestion
Emit errors for `stylelint-disable` comments that don't match rules that are specified in the configuration object.
```

2021-02-06 08:52 UTC, jeddy3 approved these changes
Thanks for making the requested changes.

LGTM!

2021-02-06 08:53 UTC, merged

2021-02-06 08:56 UTC, jeddy3 commented
> - Added: `ignoreDisables`, `reportNeedlessDisables`, `reportInvalidScopeDisables` and `reportDescriptionlessDisables` configuration object properties ([#5126](https://github.com/stylelint/stylelint/pull/5126)).