Fix false positives for Less maps (property-no-unknown)
stylelint/stylelint pull request #5381
Opened 2021-06-25 12:37 UTC by jrlmontejo

> Which issue, if any, is this issue related to?

Closes #4834 

> Is there anything in the PR that needs further explanation?

None

2021-07-13 13:10 UTC, jeddy3 requested changes
@jrlmontejo Thanks for the pull request, and apologies for just getting around to reviewing it.

Can you please:

- set to merge into the `v14` branch
- add a test to [`isStandardSyntaxDeclaration.test.js`](https://github.com/stylelint/stylelint/blob/v14/lib/utils/__tests__/isStandardSyntaxDeclaration.test.js)

I think we'll be good then.

2021-07-15 05:23 UTC, jrlmontejo commented
@jeddy3 I applied the requested changes. 

Thanks!

2021-07-15 08:41 UTC, jeddy3 approved these changes
Thanks for making the changes. LGTM.

2021-07-16 17:38 UTC, ybiquitous approved these changes
LGTM 👍🏼

2021-07-16 18:05 UTC, ybiquitous requested changes

2021-07-16 18:05 UTC, ybiquitous commented on lib/utils/isStandardSyntaxDeclaration.js
> +	if (parent.type === 'atrule' && parent.raws.afterName === ':') {
I find type errors on the `v14` branch.

```console
$ npm --silent run lint:types
lib/utils/isStandardSyntaxDeclaration.js:45:6 - error TS2532: Object is possibly 'undefined'.

45  if (parent.type === 'atrule' && parent.raws.afterName === ':') {
        ~~~~~~

lib/utils/isStandardSyntaxDeclaration.js:45:34 - error TS2532: Object is possibly 'undefined'.

45  if (parent.type === 'atrule' && parent.raws.afterName === ':') {
                                    ~~~~~~


Found 2 errors.
```

How about adding the following check?

```suggestion
	if (parent && parent.type === 'atrule' && parent.raws.afterName === ':') {
```

2021-07-19 02:15 UTC, ybiquitous approved these changes
@jrlmontejo Thank you! 👍🏼

2021-07-26 09:17 UTC, merged

2021-07-26 09:19 UTC, jeddy3 commented
v14 changelog entry:

> - Fixed: `property-no-unknown` false positives for Less maps ([#5381](https://github.com/stylelint/stylelint/pull/5381)).