Added ignoreProperties option to number-max-precision rule
stylelint/stylelint pull request #5421
Opened 2021-07-22 10:22 UTC by eljusto

> Which issue, if any, is this issue related to?

Resolved #5420 

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2021-07-26 09:34 UTC, jeddy3 requested changes
@eljusto Thank you for the pull request. Adding this option SGTM.

Can you please:

1. set the pull request to merge into the `v14` branch
2. add the option to the rule README ([like so](https://stylelint.io/user-guide/rules/list/property-no-vendor-prefix/#ignoreproperties-regex-regex-string))

2021-08-05 10:49 UTC, jeddy3 requested changes
Thanks for making the changes. I've requested two more changes as suggestions.

2021-08-05 10:49 UTC, jeddy3 commented on lib/rules/number-max-precision/README.md
> +
```suggestion

For example, with `0`.

```

We'll need to give the primary option.

2021-08-05 10:49 UTC, jeddy3 commented on lib/rules/number-max-precision/README.md
> +a { -o-transition: all 4.5s ease; }
```suggestion
a { top: 10.5px; }
```

Let's use a more common property as some users may not be familiar with the old Opera prefix.

2021-08-08 23:55 UTC, ybiquitous approved these changes
Thank you. LGTM 👍🏼

2021-08-08 23:55 UTC, ybiquitous commented on lib/rules/number-max-precision/README.md
> +```
[trivial] Specifying a language for the code block seems better to me:

````suggestion
```json
````

2021-08-10 17:36 UTC, jeddy3 approved these changes
Thanks!

2021-08-10 17:36 UTC, merged

2021-08-10 17:38 UTC, jeddy3 commented
v14 changelog entry:

> - Added: `ignoreProperties: []` to `number-max-precision` ([#5421](https://github.com/stylelint/stylelint/pull/5421)).