Fix false positives for prefers-contrast in media-feature-name-no-unknown
stylelint/stylelint pull request #5428
Opened 2021-07-27 17:47 UTC by danrichman

This is a new media query added to CSS Media Queries Level 5 to utilize the contrast preference operating systems provide.

> Which issue, if any, is this issue related to?

Closes #5427

> Is there anything in the PR that needs further explanation?

Please see issue #5427

2021-07-27 18:13 UTC, jeddy3 requested changes
Thanks for the pull request, and for using the templates here and in the issue.

I've requested a small change to fix a typo.

2021-07-27 18:13 UTC, jeddy3 commented on lib/reference/keywordSets.js
> +	'prefers-contrast'
```suggestion
	'prefers-contrast',
```

2021-07-28 08:01 UTC, jeddy3 approved these changes
Thanks, for committing the suggestion.

LGTM. 

This is being merged into [`v14` that we need help getting out the door](https://github.com/stylelint/stylelint/issues/5205). In the meantime, you can use disable comments or the [`ignoreMediaFeatureNames` secondary option](https://stylelint.io/user-guide/rules/list/media-feature-name-no-unknown/#ignoremediafeaturenames-regex-regex-string).

2021-07-28 08:25 UTC, ybiquitous approved these changes
Thanks. LGTM 👍🏼

2021-07-28 08:26 UTC, merged

2021-07-28 08:28 UTC, jeddy3 commented
Changelog entry added:

> - Fixed: `media-feature-name-no-unknown` false positives for `prefers-contrast` ([#5428](https://github.com/stylelint/stylelint/pull/5428)).