Feature/add rule selector property disallowed list
stylelint/stylelint pull request #5679
Opened 2021-10-31 13:29 UTC by doing-art

> Which issue, if any, is this issue related to?

The new rule rule-selector-property-disallowed-list that is mentioned in #5433 has been added.

> Is there anything in the PR that needs further explanation?

@jeddy3 I see that the branch `v14` has been merged and my previous [PR #5489](https://github.com/stylelint/stylelint/pull/5489), targeted to that branch, has been closed. So, I create the new one to the `main` branch. 

I made [the change](https://github.com/stylelint/stylelint/pull/5489#pullrequestreview-780769606) that you asked me to do in comments to the previous PR. Namely, added a new test which checks multiple errors.

2021-10-31 17:28 UTC, jeddy3 requested changes
@doing-art Thanks for creating a new pull request

> my previous PR #5489, targeted to that branch, has been closed

Yep, it was automatically closed by GitHub when `v14` was merged.

I've requested one last changes, otherwise LGTM.

2021-10-31 17:28 UTC, jeddy3 commented on lib/rules/rule-selector-property-disallowed-list/index.js
> +rule.primaryOptionArray = true;
```suggestion
```

We can remove this line as the primary option is an object.

2021-10-31 23:39 UTC, ybiquitous commented
@doing-art Thanks for recreating the PR!

The current HEAD revision seems a bit old because the project version specifies `13.13.1` which is not the latest version:

https://github.com/doing-art/stylelint/blob/0fcb254923ee48e14df7efc51fe997c599d1cc74/package.json#L3

The latest version is `14.0.1`:

https://github.com/stylelint/stylelint/blob/85cc19c73bc7751edca9745548d00e01252cd1c7/package.json#L3

Just in case, could you rebase the `main` branch, please?

2021-11-01 09:24 UTC, doing-art commented
> @doing-art Thanks for recreating the PR!
> 
> The current HEAD revision seems a bit old because the project version specifies `13.13.1` which is not the latest version:
> 
> https://github.com/doing-art/stylelint/blob/0fcb254923ee48e14df7efc51fe997c599d1cc74/package.json#L3
> 
> The latest version is `14.0.1`:
> 
> https://github.com/stylelint/stylelint/blob/85cc19c73bc7751edca9745548d00e01252cd1c7/package.json#L3
> 
> Just in case, could you rebase the `main` branch, please?

Thank you for your comment. I rebased `main`.

2021-11-01 09:43 UTC, ybiquitous approved these changes
@doing-art Thank you. LGTM 👍🏼

2021-11-02 15:40 UTC, jeddy3 approved these changes
Thanks!

2021-11-02 15:40 UTC, merged

2021-11-02 15:42 UTC, jeddy3 commented
Changelog entry added:

> - Added: `rule-selector-property-disallowed-list` rule ([#5679](https://github.com/stylelint/stylelint/pull/5679)).

2021-12-12 05:09 UTC, Mouvedia commented
@jeddy3 can we reuse rules internally?
By leveraging this rule we could have a meta-rule that disallow useless properties on an element.
i.e. either 1. the property is invalid (hence ignored) for that element or 2. it's superfluous (it's the default e.g. an anchor is inline)

1. is fairly easy to implement (it's just tedious)
2. is impossible (because the property might be set using JS but reset using CSS)

If that's possible then we could have a new `property-no-invalid` rule for 1. (would be limited to type selectors though).
Id advise to support both blacklisting _and_ whitelisting for the implementation.

2021-12-18 08:36 UTC, jeddy3 commented
@Mouvedia 

> can we reuse rules internally?

[Plugins can](https://stylelint.io/developer-guide/plugins#stylelintutilscheckagainstrule). 

> If that's possible then we could have a new `property-no-invalid` rule for 1

See [this plugin](https://www.npmjs.com/package/stylelint-declaration-block-no-ignored-properties) - which was removed from core a while back.

2021-12-18 13:36 UTC, Mouvedia commented
> See this plugin - which was removed from core a while back.

@jeddy3 that's not what I am talking about.
The reference, in my case, is the element.
i.e. on that element the property does nothing (**irregardless of the other properties**)
It wouldn't pose problems unlike that plugin.