better handling of function-no-unknown
stylelint/stylelint pull request #5914
Opened 2022-02-14 02:26 UTC by m4thieulavoie

This PR tweaks `function-no-unknown` so that `ignoreFunctions` are also supported in the custom properties syntax (e.g. `--primary-color: #{custom-mixin(#fff)};`

> Which issue, if any, is this issue related to?

Fixes https://github.com/stylelint/stylelint/issues/5913

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self-explanatory."

2022-02-14 14:18 UTC, jeddy3 requested changes
@m4thieulavoie Thanks for the pull request.

As per https://github.com/stylelint/stylelint/issues/5913#issuecomment-1039134269, let's check for `#{` in the [`isStandardSyntaxFunction`](https://github.com/stylelint/stylelint/blob/main/lib/utils/isStandardSyntaxFunction.js) utility instead.

You'll want to include the accept tests in [this `testRule`](https://github.com/stylelint/stylelint/blob/42c0b431d0acad67b850a75cd9f9a40fd6c0a1e2/lib/rules/function-no-unknown/__tests__/index.js#L47-L58) so that the postcss-scss custom syntax is used.

I suspect the changes you've made in this pull request to santize the node value will be useful in the stylelint-scss plugin.

2022-02-15 01:00 UTC, m4thieulavoie commented
> @m4thieulavoie Thanks for the pull request.
> 
> As per [#5913 (comment)](https://github.com/stylelint/stylelint/issues/5913#issuecomment-1039134269), let's check for `#{` in the [`isStandardSyntaxFunction`](https://github.com/stylelint/stylelint/blob/main/lib/utils/isStandardSyntaxFunction.js) utility instead.
> 
> You'll want to include the accept tests in [this `testRule`](https://github.com/stylelint/stylelint/blob/42c0b431d0acad67b850a75cd9f9a40fd6c0a1e2/lib/rules/function-no-unknown/__tests__/index.js#L47-L58) so that the postcss-scss custom syntax is used.
> 
> I suspect the changes you've made in this pull request to sanitize the node value will be useful in the stylelint-scss plugin if they add a `scss/function-no-unknown` rule. Let's revert them in this pull request, though.

That should be done 👍 Let me know what you think!

2022-02-15 14:22 UTC, jeddy3 approved these changes
Thank you for making the changes.

LGTM.

2022-02-15 23:21 UTC, ybiquitous approved these changes
@m4thieulavoie Thank you. LGTM 👍🏼

2022-02-15 23:23 UTC, merged

2022-02-15 23:25 UTC, ybiquitous commented
Updated the changelog:

> Fixed: `function-no-unknown` false positives for interpolation ([#5914](https://github.com/stylelint/stylelint/pull/5914)).