Fix false positives for interpolation in property name in custom-property-pattern
stylelint/stylelint pull request #5949
Opened 2022-03-02 23:08 UTC by kawaguchi1102

> Which issue, if any, is this issue related to?

Closes #5945

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2022-03-03 14:49 UTC, jeddy3 requested changes
@kawaguchi1102 Thanks for jumping on this.

Changes to rule code LGTM.

I've requested changes to the tests (as committable suggestions) to bring them in line with [our conventions](https://stylelint.io/developer-guide/rules#write-tests).

---

Note: You can either refactor in this pull request (or we can create a follow-up issue) to move the duplicated code into `check(property) {}` function. It's up to you.

2022-03-03 14:49 UTC, jeddy3 commented on lib/rules/custom-property-pattern/__tests__/index.js
> +			code: 'a { color: var( #{$variable-color} ); }',
```suggestion
			code: 'a { color: var( #{$bar} ); }',
```

2022-03-04 12:34 UTC, kawaguchi1102 commented
@jeddy3 Sorry, I must have missed it.
i've updated it now with what you said.

---

> Note: You can either refactor in this pull request (or we can create a follow-up issue) to move the duplicated code into `check(property) {}` function. It's up to you.

That's a good idea!
I'll refactor with this PR.

2022-03-05 16:35 UTC, kawaguchi1102 commented
@jeddy3 The refactor has been completed.
I hope I am not mistaken in this refactor.

2022-03-06 18:50 UTC, jeddy3 reviewed
Thanks for making the changes. LGTM!

> I hope I am not mistaken in this refactor.

It's looks spot on to me, thank you.

2022-03-06 18:50 UTC, jeddy3 approved these changes

2022-03-07 00:16 UTC, ybiquitous approved these changes
Thank you! LGTM 👍🏼

2022-03-07 09:55 UTC, merged

2022-03-07 09:57 UTC, jeddy3 commented
> - Fixed: `custom-property-pattern` false positives for interpolation in property name ([#5949](https://github.com/stylelint/stylelint/pull/5949)).