Add support for vendor prefixes in ﻿`property-*-list`
stylelint/stylelint pull request #6025
Opened 2022-04-19 15:01 UTC by carlosjeurissen

> Which issue, if any, is this issue related to?

Closes https://github.com/stylelint/stylelint/issues/5981

> Is there anything in the PR that needs further explanation?

The parameter types for matchesStringOrRegExp had to be fixed. It didn't include Array<string>.

2022-04-19 15:37 UTC, ybiquitous requested changes
@carlosjeurissen Thank you so much for the first contribution!

In addition, can you address the following?

- Add a simple test case for the rule change.
- Fix also the `property-allowed-list` rule in the same way.
  - https://github.com/stylelint/stylelint/blob/b013ac0827fede2547ba478e920956ff5739af8e/lib/rules/property-allowed-list/index.js#L45

2022-04-19 15:39 UTC, ybiquitous commented
Ah, I've overlapped with @jeddy3 😅

2022-04-19 15:40 UTC, ybiquitous commented
@jeddy3 Do you think it's necessary to remove the `unprefixed` word from the rule doc?

https://github.com/stylelint/stylelint/blob/b013ac0827fede2547ba478e920956ff5739af8e/lib/rules/property-disallowed-list/README.md?plain=1#L14

2022-04-19 20:32 UTC, carlosjeurissen commented
Addressed the `property-allowed-list`, `README.md` and the tests. Thanks for the suggestions!

2022-04-20 00:13 UTC, ybiquitous approved these changes
Great. LGTM 👍🏼

2022-04-20 07:14 UTC, jeddy3 approved these changes
LGTM, thank you!

2022-04-20 07:14 UTC, merged

2022-04-20 07:15 UTC, jeddy3 commented
Changelog entry added:

> - Added: `property-*-list` support for vendor prefixes ([#6025](https://github.com/stylelint/stylelint/pull/6025)).