Add rule `import-notation`
stylelint/stylelint pull request #6102
Opened 2022-05-20 22:58 UTC by playhardgopro

> Which issue, if any, is this issue related to?

Closes #4055 

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2022-05-21 03:13 UTC, ybiquitous requested changes
@playhardgopro Thank you for the contirubtion! This addition looks almost good to me. 👍🏼 

I've left suggestions about trivial things. Please consider fixing them.

In addition, can you please also the following doc to add a new section `Imports` and a link to the new rule?

https://github.com/stylelint/stylelint/blob/e1e28fec4b4f1a98fc94d81b7ffa0cdb393242ac/docs/user-guide/rules/list.md?plain=1#L94

2022-05-21 03:13 UTC, ybiquitous commented on lib/rules/import-notation/index.js
> +const valueParser = require('postcss-value-parser');
[suggest] Separate external and internal `require()` between an empty line.

```suggestion
const valueParser = require('postcss-value-parser');

const report = require('../../utils/report');
const ruleMessages = require('../../utils/ruleMessages');
const validateOptions = require('../../utils/validateOptions');
```

2022-05-21 03:13 UTC, ybiquitous commented on lib/rules/import-notation/index.js
> +		root.walkAtRules('import', checkAtRuleImportParams);
[suggestion] Better to support case-insensitive `@import`.

```suggestion
		root.walkAtRules(/^import$/i, checkAtRuleImportParams);
```

2022-05-21 07:36 UTC, playhardgopro commented
@ybiquitous I added all suggested changes, thanks for review!

2022-05-21 08:47 UTC, ybiquitous reviewed
@playhardgopro Thank you! Additionally, I suggest trivial fixes on the doc.

2022-05-21 08:47 UTC, ybiquitous commented on docs/user-guide/rules/list.md
> +- [`import-notation`](../../../lib/rules/import-notation/README.md): Specify string or url notation for imports.
```suggestion
- [`import-notation`](../../../lib/rules/import-notation/README.md): Specify string or url notation for imports (Autofixable).
```

2022-05-21 08:47 UTC, ybiquitous commented on lib/rules/import-notation/README.md
> +Imports _must_ use _url_ function.
```suggestion
Imports _must_ use the `url` function.
```

2022-05-21 09:48 UTC, ybiquitous approved these changes
Thanks, LGTM 👍🏼

2022-05-21 13:09 UTC, ybiquitous commented
Just in case, I'd like to wait for @jeddy3's review.

2022-06-06 10:22 UTC, jeddy3 requested changes
@playhardgopro Thanks for the pull request! It's looking good.

I've requested some changes. The two biggest are:
- the structure of the problem message
- how unquoted values are handled

The other changes are mainly trivial doc changes to be consistent with other rules.

2022-06-06 10:22 UTC, jeddy3 commented on lib/rules/import-notation/index.js
> +	expected: (importUrlOrString, primary) => `Expected "${importUrlOrString}" to be a "${primary}"`,
```suggestion
	expected: (unfixed, fixed) => `Expected "${unfixed}" to be "${fixed}"`,
```

My bad, I got this wrong in [the blueprint](https://github.com/stylelint/stylelint/issues/4055#issuecomment-1014768867).

We use the:
- "Expected x to be y" message format when showing the fixed values, e.g. https://github.com/stylelint/stylelint/blob/9d045d928699c0d84b86e08a3d8b035343b06ca4/lib/rules/alpha-value-notation/index.js#L18
- "Expected primary option" message format when we don't, e.g. https://github.com/stylelint/stylelint/blob/9d045d928699c0d84b86e08a3d8b035343b06ca4/lib/rules/color-function-notation/index.js#L17

We should use the former here as:
- it's generally more useful for users
- the URL/string parts of `@import` rules are generally short

e.g. "Expected '"foo.css"' to be 'url("foo.css")' (import-notation)"

We'll need to use single quotes if there are double quotes in the value, and vice-versa.

2022-06-06 10:22 UTC, jeddy3 commented on lib/rules/import-notation/__tests__/index.js
> +		},
```suggestion
```

Let's ignore invalid CSS.

2022-06-06 10:22 UTC, jeddy3 commented on lib/rules/import-notation/__tests__/index.js
> +			fixed: '@import foo.css;',
```suggestion
			fixed: '@import "foo.css";',
```

Let's default to double quotes.

2022-06-06 10:22 UTC, jeddy3 commented on lib/rules/import-notation/__tests__/index.js
> +			fixed: '@import foo.css print;',
```suggestion
			fixed: '@import "foo.css" print;',
```

Let's default to double quotes (otherwise we're generating invalid CSS).

2022-06-06 10:22 UTC, jeddy3 commented on lib/rules/import-notation/__tests__/index.js
> +		},
```suggestion
```

Let's not fixed invalid CSS.

2022-06-07 09:57 UTC, jeddy3 approved these changes
@playhardgopro Fantastic! Thanks for making all the changes.

LGTM.

2022-06-07 09:58 UTC, merged

2022-06-07 10:00 UTC, jeddy3 commented
Changelog entry:

> - Added: `import-notation` rule ([#6102](https://github.com/stylelint/stylelint/pull/6102)).