Publicly expose reference data
stylelint/stylelint pull request #6152
Opened 2022-06-15 01:23 UTC by nex3

Closes #6151

2022-06-15 14:49 UTC, ybiquitous requested changes
@nex3 Thanks for creating the pull request!

I think there are no significant problems. Could you consider addressing my review comments? Of course, you can do it after the discussion.

2022-06-15 14:49 UTC, ybiquitous commented on types/stylelint/index.d.ts
> +		export type KeywordSets = {
[suggest] Could you add a type annotation to each module like this? By doing so, we could improve the code's type safety.

```js
// lib/reference/keywordSets.js

/** @type {import('stylelint').KeywordSets} */
const keywordSets = {};

// ...

module.exports = (keywordSets);
```
```

2022-06-15 14:49 UTC, ybiquitous commented on CHANGELOG.md
> +
[suggest] Could you revert the change, please? We will update the changelog after merged.

```suggestion
```

2022-06-15 14:49 UTC, ybiquitous commented on package.json
> +  "version": "14.10.0",
[suggest] Could you revert the version, please? It will be automatically updated on release.

```suggestion
  "version": "14.9.1",
```

2022-06-24 21:05 UTC, nex3 commented
I'm going to close this out in favor of https://github.com/stylelint/stylelint/pull/6168, which is a more principled approach to the same goal.

2022-06-24 21:05 UTC, closed without merging