Add support for loading custom formatter from package when using PnP
stylelint/stylelint pull request #6228
Opened 2022-07-27 19:26 UTC by meriouma

> Which issue, if any, is this issue related to?

Closes #6100

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self-explanatory."

2022-07-27 22:08 UTC, JounQin requested changes

2022-07-27 22:08 UTC, JounQin commented on lib/resolveCustomFormatter.js
> +	return formatterPath;
It should call `require.resolve` here to ensure the path is correct.

2022-07-27 22:59 UTC, JounQin approved these changes

2022-07-28 00:53 UTC, JounQin requested changes

2022-07-28 00:53 UTC, JounQin commented on lib/resolveCustomFormatter.js
> +	const relativePath = path.join(process.cwd(), formatterPath);
I'd prefer to use `path.resolve` which covers the case for absolute path.

2022-07-28 01:26 UTC, JounQin requested changes

2022-07-28 01:26 UTC, JounQin commented on lib/resolveCustomFormatter.js
> +	const relativePath = path.join(process.cwd(), formatterPath);
```suggestion
	const relativePath = path.resolve(process.cwd(), formatterPath);
```

2022-07-28 01:27 UTC, JounQin requested changes

2022-07-28 01:27 UTC, JounQin commented on lib/resolveCustomFormatter.js
> +	}
```suggestion
	if (fs.existsSync(formatterPath)) {
		return formatterPath;
	}
```

2022-07-28 01:42 UTC, JounQin commented on lib/__tests__/resolveCustomFormatter.test.js
> +		expect(result).toEqual(expect.stringMatching(RegExp(`${expectedPath}$`)));
```suggestion

		expect(result).toEqual(expect.stringMatching(RegExp(`${expectedPath}$`)));
```

2022-07-28 01:43 UTC, JounQin commented on lib/__tests__/resolveCustomFormatter.test.js
> +		path.isAbsolute.mockReturnValue(false);
```suggestion
```

2022-07-28 01:45 UTC, JounQin commented on lib/__tests__/resolveCustomFormatter.test.js
> +		expect(result).toEqual(expect.stringMatching(RegExp(`${expectedPath}$`)));
```suggestion
		expect(result).toEqual(expectedPath);
```

2022-07-28 01:46 UTC, meriouma commented on lib/__tests__/resolveCustomFormatter.test.js
> +jest.mock('path');
I believe this is inconsistent with the other test files.

2022-07-28 01:47 UTC, JounQin commented on lib/__tests__/resolveCustomFormatter.test.js
> +		const expectedPath = realPathModule.join('node_modules', aModulePath);
```suggestion
		const expectedPath = realPathModule.resolve('node_modules', aModulePath);
```

2022-07-28 01:48 UTC, JounQin commented
@meriouma Don't do suqash locally, keep the commits history, that's fine. We'll merge with squash.

2022-07-28 01:50 UTC, JounQin commented on lib/__tests__/resolveCustomFormatter.test.js
> +		const expectedPath = realPathModule.resolve('node_modules', aModulePath);
```suggestion
		const expectedPath = realPathModule.resolve('lib/__tests__/node_modules', aModulePath);
```

2022-07-28 01:59 UTC, JounQin commented on lib/__tests__/resolveCustomFormatter.test.js
> +		expect(result).toEqual(expectedPath);
```suggestion
		const expectedPath = realPathModule.join('node_modules', aModulePath);

		expect(result.endsWith(expectedPath)).toBe(true);
```

2022-07-28 02:08 UTC, JounQin approved these changes

2022-07-28 02:59 UTC, ybiquitous reviewed
The change looks good to me. I've left a suggestion for testing.

2022-07-28 02:59 UTC, ybiquitous commented on lib/cli.js
Could you add a test case to cover the code calling `resolveCustomFormatter()` to `cli.test.js`?

2022-07-28 04:17 UTC, ybiquitous requested changes
[suggest] Sorry, I missed one point. Could you make single exporting consistent with other modules?

2022-07-28 04:17 UTC, ybiquitous commented on lib/__tests__/resolveCustomFormatter.test.js
> +const { resolveCustomFormatter } = require('../resolveCustomFormatter');
```suggestion
const resolveCustomFormatter = require('../resolveCustomFormatter');
```

2022-07-28 04:17 UTC, ybiquitous commented on lib/cli.js
> +const { resolveCustomFormatter } = require('./resolveCustomFormatter');
```suggestion
const resolveCustomFormatter = require('./resolveCustomFormatter');
```

2022-07-28 04:17 UTC, ybiquitous commented on lib/resolveCustomFormatter.js
> +};
```suggestion
module.exports = function resolveCustomFormatter(formatterPath) {
	const resolvedPath = path.resolve(formatterPath);

	if (fs.existsSync(resolvedPath)) {
		return resolvedPath;
	}

	return require.resolve(formatterPath);
};
```

2022-07-28 04:24 UTC, ybiquitous requested changes
[suggest] I think it's good to improve the CLI help and the doc about the `--custom-formatter` option. It will support a package name, not only a relative/absolute file path.

Could you update also the following files?

https://github.com/stylelint/stylelint/blob/743030d1bda238cfdb4b1aede456f34504d8824d/lib/cli.js#L178-L180

https://github.com/stylelint/stylelint/blob/743030d1bda238cfdb4b1aede456f34504d8824d/docs/user-guide/usage/options.md?plain=1#L91

2022-07-28 08:52 UTC, JounQin commented
@meriouma Are you still working on this?

2022-07-28 14:54 UTC, meriouma commented
@JounQin Yes, I will apply the changes. I stopped pushing changes yesterday so we were not two persons pushing in the branch at the same time.

2022-07-28 15:01 UTC, JounQin commented
> @JounQin Yes, I will apply the changes. I stopped pushing changes yesterday so we were not two persons pushing in the branch at the same time.

You'll only need to pull the latest codes and then continue the work. 🍺

2022-07-28 15:41 UTC, JounQin requested changes

2022-07-28 15:41 UTC, JounQin commented on lib/__tests__/__snapshots__/cli.test.js.snap
> +      The file can either be a filesystem path, or a file to load from a dependency.
A module name is also file.

2022-07-28 16:09 UTC, ybiquitous commented
@meriouma Thank you for addressing the requested changes! The PR looks almost good to me.

I got an idea to test a custom formatter dependency in the repository: to install a private internal dependency. For example:

`package.json`:

```json
{
  "devDependencies": {
    "stylelint-test-custom-formatter": "file:packages/stylelint-test-custom-formatter"
  }
}
```

`packages/`:

```console
$ tree packages
packages/
└── stylelint-test-custom-formatter/
    ├── index.js
    └── package.json

1 directory, 2 files
```

Run a test:

```console
$ bin/stylelint.js --config=scripts/visual-config.json --custom-formatter=stylelint-test-custom-formatter scripts/*.css
Custom formatter reports 1 warning(s).%
```

What do you think about this idea?

2022-07-28 16:21 UTC, ybiquitous commented
@JounQin I thought about how to test the dependency behavior without mocking. But mocking dependency resolution in `cli.test.js` may be enough and straightforward.

2022-07-28 16:28 UTC, JounQin commented
> @JounQin I thought about how to test the dependency behavior without mocking. But mocking dependency resolution in `cli.test.js` may be enough and straightforward.

Yeah, a mock module like https://github.com/stylelint/stylelint/blob/main/lib/__tests__/__mocks__/get-stdin.js is fine IMO.

(Besides, https://github.com/stylelint/stylelint/blob/main/lib/__tests__/__mocks__/get-stdin.js seems can be deleted safely in favor of #6182

2022-07-28 23:37 UTC, ybiquitous approved these changes
Great! LGTM 👍🏼

2022-07-29 00:03 UTC, JounQin approved these changes

2022-07-29 00:03 UTC, merged

2022-07-29 00:04 UTC, JounQin commented
@meriouma Thanks for your contribution!

2022-07-29 00:11 UTC, ybiquitous commented
Changelog entry added:

> - Added: support for loading custom formatter from package ([#6228](https://github.com/stylelint/stylelint/pull/6228)).