Fix false positives for interpolation in keyframes-name-pattern #5997
stylelint/stylelint pull request #6265
Opened 2022-08-14 09:03 UTC by a-falkonia

> Which issue, if any, is this issue related to?

Closes #5997 

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2022-08-14 11:54 UTC, jeddy3 requested changes
@a-falkonia Thanks for opening the pull request. It's looking good.

I've requested some minor changes.

2022-08-14 11:54 UTC, jeddy3 commented on lib/rules/keyframes-name-pattern/index.js
> +			if (!isStandardSyntaxKeyframesName(value)) {
Let's move this to before the first conditionally as we normally check that things are standard before any other operation.

2022-08-14 11:54 UTC, jeddy3 commented on lib/utils/__tests__/isStandardSyntaxKeyframesName.test.js
> +		expect(isStandardSyntaxKeyframesName('@keyframes slidein {}')).toBeTruthy();
```suggestion
		expect(isStandardSyntaxKeyframesName('slidein')).toBeTruthy();
```

As the util is checking the [keyframes-name](https://drafts.csswg.org/css-animations/#typedef-keyframes-name), and not the whole `@keyframe`.

We'll need to update the other tests too.

2022-08-14 11:54 UTC, jeddy3 commented on lib/utils/isStandardSyntaxKeyframesName.js
> +	// SCSS or Less interpolation
```suggestion
```

We can loose the comment. (The `hasInterpolation` checks for more than just Less or Sass interpolation).

2022-08-15 17:22 UTC, a-falkonia commented
@jeddy3 Thank you for your review!
I've made the required changes, hope everything looks good now.

2022-08-16 03:41 UTC, ybiquitous reviewed
@a-falkonia Thanks for creating the PR!

I've left some refactoring suggestions, but the change looks almost good. 👍🏼

2022-08-16 03:41 UTC, ybiquitous commented on lib/utils/__tests__/isStandardSyntaxKeyframesName.test.js
> +		expect(isStandardSyntaxKeyframesName('slidein {}')).toBeTruthy();
[suggest] `toBe(true)` / `toBe(false)` are more accurate than `toBeTruthy()` / `toBeFalsy()`. E.g.

```suggestion
		expect(isStandardSyntaxKeyframesName('slidein {}')).toBe(true);
```

2022-08-16 03:41 UTC, ybiquitous commented on lib/utils/isStandardSyntaxKeyframesName.js
> +
[trivial] Can you please remove the empty line for consistency?

```suggestion
```

2022-08-16 03:41 UTC, ybiquitous commented on lib/utils/isStandardSyntaxKeyframesName.js
> +module.exports = function (keyframesName) {
[suggest] Can you please give a function name for debuggability (avoiding anonymous functions)?

```suggestion
module.exports = function isStandardSyntaxKeyframesName(keyframesName) {
```

2022-08-16 06:10 UTC, a-falkonia commented
@ybiquitous Thank you! I've made the updates.

2022-08-16 06:14 UTC, ybiquitous approved these changes
Thank you! LGTM 👍🏼

2022-08-16 17:41 UTC, jeddy3 requested changes
@a-falkonia Thanks for making the changes. All most there.

I've requested one set of minor changes to the tests.

2022-08-16 18:07 UTC, a-falkonia commented
@jeddy3 So so sorry for missing this. All the blocks should be removed now.

2022-08-16 18:35 UTC, jeddy3 approved these changes
Thank you!

2022-08-16 18:37 UTC, jeddy3 commented
Changelog entry added:

> - Fixed: `keyframes-name-pattern` false positives for interpolation ([#6265](https://github.com/stylelint/stylelint/pull/6265)).

2022-08-16 18:38 UTC, merged