Fix type declarations for custom message arguments
stylelint/stylelint pull request #6354
Opened 2022-09-19 13:55 UTC by stof

> Which issue, if any, is this issue related to?

Closes #6353

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self-explanatory."

2022-09-20 00:55 UTC, ybiquitous requested changes
@stof Thanks for your first PR contribution. I couldn't notice the type error due to `skipLibCheck: false`.

I appreciate your report right after the 14.12.0 release. 👍🏼

2022-09-20 00:55 UTC, ybiquitous commented on .changeset/eleven-monkeys-return.md
> +Fix type declarations for custom message arguments
[suggest] Thanks for adding the entry. Please fit the prefix to the existing format in `CHANGELOG.md` as below:

```suggestion
Fixed: type declarations for custom message arguments
```

2022-09-20 00:55 UTC, ybiquitous commented on tsconfig.json
> -		"skipLibCheck": true,
[suggest] Can you change `true` to `false` to make it easier for us to find a commit history?

```diff
-"skipLibCheck": true,
+"skipLibCheck": false,
```

2022-09-20 12:28 UTC, ybiquitous approved these changes
Thank you. LGTM 👍🏼

2022-09-20 12:32 UTC, merged

2022-09-20 12:39 UTC, stof commented
@ybiquitous do you have any estimate about when the fix will be released ?

2022-09-20 12:48 UTC, ybiquitous commented
@stof Perhaps within a few days.

2022-09-20 13:01 UTC, stof commented
thanks

2022-09-21 12:45 UTC, ybiquitous commented
[14.12.1](https://github.com/stylelint/stylelint/releases/tag/14.12.1) is released!