Make preparing GitHub Release easier
stylelint/stylelint pull request #6371
Opened 2022-09-28 15:37 UTC by ybiquitous

> Which issue, if any, is this issue related to?

Ref: https://github.com/stylelint/stylelint/issues/6343#issuecomment-1250353973

> Is there anything in the PR that needs further explanation?

I believe this PR can omit the following step of releasing:

https://github.com/stylelint/stylelint/blob/eee9deb35190f46c5f964769d521fef5d7d1d7a8/docs/maintainer-guide/releases.md?plain=1#L16

This is not just a copy-and-paste of `CHANGELOG.md`. Instead, it rewrites user links to user mentions (e.g. `@ybiquitous`) so that the "Contributors" section should be displayed on a release page [like this](https://github.com/postcss/postcss/releases/tag/8.4.14).

But, one downside. This PR increase complexity: a remark script and a GitHub action. It may be too much for this automation. I'll close the PR if anyone expresses a concern.

2022-09-28 16:20 UTC, ybiquitous commented on .github/workflows/preparing-github-release.yml
> +        run: gh release create "${GITHUB_REF_NAME}" --draft --notes-file /tmp/changes.md
See also https://cli.github.com/manual/gh_release_create

2022-09-29 07:43 UTC, jeddy3 requested changes
Thanks for this! Looks good.

> But, one downside. This PR increase complexity: a remark script and a GitHub action. It may be too much for this automation. I'll close the PR if anyone expresses a concern.

There's no harm in trying it out. If the complexity proves problematic later down the line we can remove it and revert to the manual method.

Let's remove the corresponding step in the release doc as part of this PR.

2022-09-29 08:16 UTC, ybiquitous commented
@jeddy3 Thanks for the feedback! I've updated the releasing guide via fddc0da3b.

2022-09-29 08:23 UTC, merged

2022-09-29 08:26 UTC, ybiquitous commented
If this new workflow is not as expected in the next release, let's recover it manually.