Fix declaration-block-no-duplicate-properties autofix for !important
stylelint/stylelint pull request #6528
Opened 2022-12-16 03:37 UTC by sidx1024

> Which issue, if any, is this issue related to?

Fixes https://github.com/stylelint/stylelint/issues/6523

> Is there anything in the PR that needs further explanation?

No, that's it.

2022-12-16 05:22 UTC, ybiquitous requested changes
@sidx1024 Thanks for creating the PR! Additionally, could you add test cases to `testRule` with other secondary options?

- `ignore: [ 'consecutive-duplicates-with-different-values' ]`
- `ignore: [ 'consecutive-duplicates-with-same-prefixless-values' ]`
- `ignoreProperties: [ 'color' ]`

2022-12-19 11:53 UTC, sidx1024 commented
@ybiquitous Added the requested test cases.

2022-12-20 01:22 UTC, ybiquitous requested changes
@sidx1024 Thank you. Could you address one more suggestion, please?

2022-12-20 01:22 UTC, ybiquitous commented on lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
> +		},
[suggest] To cover the following line,

```
lib/rules/declaration-block-no-duplicate-properties/index.js#L125

Added line #L125 was not covered by tests
```

could you please add a more test case?

```suggestion
		},
		{
			code: 'p { width: 100% !important; width: -moz-fit-content; }',
			fixed: 'p { width: 100% !important; }',
			message: messages.rejected('width'),
		},
```

2022-12-20 06:16 UTC, ybiquitous approved these changes
Thanks. LGTM 👍🏼

2022-12-23 06:50 UTC, merged