Export types needed for plugin authoring
stylelint/stylelint pull request #6664
Opened 2023-02-15 14:41 UTC by henryruhs

Export types for plugin authoring.

Related to https://github.com/stylelint/stylelint/issues/6662

2023-02-15 22:55 UTC, ybiquitous requested changes
@henryruhs Thanks for the pull request. `npm run lint:types` fails. Could you please check it?

I'll add a changeset later; no worries.

2023-02-15 23:06 UTC, henryruhs commented
I fixed it, sorry for that

2023-02-16 00:50 UTC, ybiquitous requested changes
Thanks for fixing the errors. I've left a few minor suggestions. Please consider addressing them.

2023-02-16 00:50 UTC, ybiquitous commented on types/stylelint/index.d.ts
> +	export type Plugin =
[suggest] Can you also add JSDOC, please?

```suggestion
	/**
	 * A Stylelint plugin.
	 */
	export type Plugin =
```

2023-02-16 00:50 UTC, ybiquitous commented on types/stylelint/index.d.ts
> +	export type RuleContext = {
[suggest] Also here:

```suggestion
	/**
	 * A rule context.
	 */
	export type RuleContext = {
```

2023-02-16 00:50 UTC, ybiquitous commented on types/stylelint/index.d.ts
> +
[suggest] Let's remove the new type to minimize this pull request change. Perhaps, later refactoring PRs may add similar types.

```suggestion
```

2023-02-16 08:35 UTC, henryruhs commented
Requested changes have been applied

2023-02-16 09:44 UTC, ybiquitous approved these changes
Thank you! LGTM 👍🏼

2023-02-16 12:47 UTC, jeddy3 approved these changes
LGTM, thank you!

2023-02-16 12:48 UTC, merged