Add `-c` alias for `--config`
stylelint/stylelint pull request #6720
Opened 2023-03-20 11:11 UTC by sidverma32

> Which issue, if any, is this issue related to?

Closes #6690 

> Is there anything in the PR that needs further explanation?

Refer to this discussion:
https://github.com/stylelint/stylelint/pull/6617#discussion_r1121431016)

2023-03-20 12:55 UTC, ybiquitous requested changes
[suggest] Can you add a new changelog entry with this PR title? The [changeset-bot instruction](https://github.com/stylelint/stylelint/pull/6720#issuecomment-1476036536) should be helpful.

Like this:

```yaml
---
"stylelint": minor
---

Added: `-c` alias for `--config`
```

2023-03-20 13:15 UTC, Mouvedia commented on lib/__tests__/__snapshots__/cli.test.js.snap
> +    --config , -c
```suggestion
    --config, -c
```

2023-03-20 13:24 UTC, ybiquitous approved these changes
Thanks, LGTM 👍🏼

2023-03-21 05:37 UTC, sidverma32 commented
> Thanks, LGTM 👍🏼

Shall I merge?

2023-03-21 06:53 UTC, merged