Refactor to remove unneeded `isStandardSyntaxMediaFeature` utilities
stylelint/stylelint pull request #7021
Opened 2023-06-30 20:47 UTC by romainmenke

> Which issue, if any, is this issue related to?

Closes https://github.com/stylelint/stylelint/issues/6848

> Is there anything in the PR that needs further explanation?

These utilities aren't needed anymore.  
`@csstools/media-query-list-parser` only parses standard CSS as media feature AST nodes.

------

I think #6848 can be closed as completed after this change.

2023-06-30 21:12 UTC, Mouvedia commented
Can we wait for elirasza/stylelint-stylistic to be refactored first?

https://github.com/elirasza/stylelint-stylistic/blob/dce7ea440d44a8e6aa28251eca4e3fbd98a376ba/lib/rules/media-feature-name-case/index.js#L5

2023-06-30 21:26 UTC, romainmenke commented
I didn't know the functions from `utils` were part of the public API of Stylint.
I assumed they were not given this comment : https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/plugins.md#external-helper-modules

---

I will restore these files.

2023-06-30 21:29 UTC, Mouvedia commented
@romainmenke it's complicated: #6866

2023-07-01 00:25 UTC, ybiquitous commented
To be honest, I'm not in favor of leaving unused and internal modules (see also <https://github.com/stylelint/stylelint/issues/6866#issuecomment-1567565404>). As a maintainer, I feel it isn't easy to care about internal modules used by plugins. 😓 

However, only this time, we've removed many utilities toward v16 (see #7002), so we can delay removing unused modules. I think it's acceptable to remove `isStandardSyntaxMediaFeatureName` on the `v16` branch.

Could you open a new PR to remove it for `v16`?

2023-07-01 00:27 UTC, ybiquitous approved these changes
Anyway, the series of refactoring work for #6848 is great! 👏🏼 

Thank you so much for your effort! @romainmenke

2023-07-01 07:51 UTC, jeddy3 requested changes
Thank you.

Two minor requests, otherwise LGTM.

> Anyway, the series of refactoring work for https://github.com/stylelint/stylelint/issues/6848 is great! 👏🏼

Totally agree!

2023-07-01 07:51 UTC, jeddy3 commented on lib/rules/media-feature-name-allowed-list/__tests__/index.js
> +		},
```suggestion
```

This is covered by line 208.

(For future reference, we typically put non-standard cases into their own `testRule` with the appropriate non-standard syntax to separate standard from non-standard.)

2023-07-01 07:51 UTC, jeddy3 commented on lib/rules/media-feature-name-case/__tests__/index.js
> +		},
```suggestion
```

Covered by line 312.

2023-07-01 07:56 UTC, romainmenke commented on lib/rules/media-feature-name-case/__tests__/index.js
> -		},
I was checking if this would hit a specific code bath, but it didn't.
I forgot to remove it again.

2023-07-01 07:57 UTC, jeddy3 approved these changes
LGTM, thank you!

2023-07-01 08:05 UTC, romainmenke commented
Thank you again for the reviews on all this 🙇 
Awesome to wrap this up!

2023-07-01 08:05 UTC, merged