Add lightness-notation
stylelint/stylelint pull request #7366
Opened 2023-12-02 15:10 UTC by fpetrakov

Closes #7359 

> Is there anything in the PR that needs further explanation?

No, it's self explanatory.

2023-12-04 13:11 UTC, romainmenke reviewed
Thank you for the fixed @fpetrakov

2023-12-04 13:11 UTC, romainmenke commented on lib/rules/lightness-notation/index.cjs
> +	}
I think this can be omitted?

2023-12-04 13:11 UTC, romainmenke commented on lib/rules/lightness-notation/index.cjs
>  	const dimension = valueParser.unit(value);
Why not reuse the parsed number that is returned here?

I think it's better to use that, than to have `parseFloat(value)` and `value.slice(0, -1)`.

2023-12-04 16:12 UTC, romainmenke commented on lib/rules/lightness-notation/index.cjs
> +	}
thank you for explaining

2023-12-05 06:32 UTC, ybiquitous requested changes
@fpetrakov Thanks for creating the PR. I don't believe there are major problems. 👍🏼 

Can you take a look at my suggestion comments? If you have rationale, you don't need to address all.

2023-12-05 06:32 UTC, ybiquitous commented on lib/rules/lightness-notation/index.mjs
> +				if (!LIGHTNESS_FUNCS.has(node.value.toLowerCase())) return;
[suggest] Can we move the `functionName` declaration at [L66](https://github.com/stylelint/stylelint/pull/7366/files#diff-e55c9791f54478934c2ad8ddd81e2913441c88b5ba16638f72d10ba02214c11aR66) to here?

```suggestion
				const functionName = node.value.toLowerCase();

				if (!LIGHTNESS_FUNCS.has(functionName)) return;
```

2023-12-05 06:32 UTC, ybiquitous commented on lib/rules/lightness-notation/index.mjs
> +	return undefined;
[suggest] How about simplifying `findLightness()` like this? `LIGHTNESS_FUNCS.has()` check seems duplicate at [L50](https://github.com/stylelint/stylelint/pull/7366/files#diff-e55c9791f54478934c2ad8ddd81e2913441c88b5ba16638f72d10ba02214c11aR50).

```suggestion
function findLightness({ nodes }) {
	return nodes.find(({ type }) => type === 'word' || type === 'function');
```

2023-12-05 06:32 UTC, ybiquitous commented on lib/rules/lightness-notation/index.mjs
> +				if (!isStandardSyntaxValue(value)) return;
[suggest] I'm concerned about redundant calls of `valueParser.unit()`. How about reducing the calls like this?

```suggestion
				if (!isStandardSyntaxValue(value)) return;

				const dimension = valueParser.unit(value);

				if (!dimension) return;

				const isPercentage = dimension.unit === '%';
				const isNumber = dimension.unit === '';
```

2023-12-05 06:32 UTC, ybiquitous commented on lib/rules/lightness-notation/README.md
[suggest] How about adding supported functions like `oklch` to this README?

2023-12-05 06:33 UTC, ybiquitous commented
Note: I'd like to merge this PR after the 16.0.0 release (#7374).

2023-12-05 08:18 UTC, fpetrakov commented
@ybiquitous Thanks for reviewing the PR. All of yours suggestions are sensible, so I will fix them in the coming days

2023-12-05 14:09 UTC, Mouvedia commented on lib/rules/lightness-notation/index.mjs
> +]);
https://github.com/stylelint/stylelint/blob/7e54fd597230170c30ad30303d0d41fc2b845396/lib/reference/functions.mjs#L15 could be constructed from 2 sets.
IMHO the granularity of ZERO_TO_ONE vs ZERO_TO_HUNDRED is localized and not worth exposing outside of this rule.

2023-12-05 14:28 UTC, ybiquitous commented on lib/rules/lightness-notation/index.mjs
> +]);
Make sense.

2023-12-05 15:02 UTC, Mouvedia commented on lib/rules/lightness-notation/index.mjs
> +				const unfixed = value;
minor

You could instead rename it at l57.
i.e. `const { value: unfixed } = lightness;`

2023-12-05 16:10 UTC, ybiquitous commented on lib/utils/dimensionUnitIsEmpty.cjs
Can you remove this file, too?

2023-12-05 16:15 UTC, ybiquitous approved these changes
Thanks, LGTM. I'll revisit this after the 16.0.0 release.

Also, we need to determine a value (maybe `percentage`?) added in the standard config before publishing this new rule.

2023-12-05 16:16 UTC, fpetrakov commented
> Also, we need to determine a value (maybe `percentage`?) added in the standard config before publishing this new rule.

I agree on `percentage`

2023-12-10 16:52 UTC, ybiquitous commented
@fpetrakov Can you resolve the conflicts raised by the 16.0.0 release?

2023-12-10 17:10 UTC, jeddy3 requested changes
Thank you! It's looking great.

I've requested a change to the README, otherwise LGTM.

2023-12-10 17:10 UTC, jeddy3 commented on lib/rules/lightness-notation/README.md
> +
```suggestion
```

We tend to keep our README examples as small as possible. Two should be enough: one showing a 0-1 percentage range and the other a 1-100 range.

2023-12-10 17:10 UTC, jeddy3 commented on lib/rules/lightness-notation/README.md
> +```
```suggestion
```

2023-12-10 17:10 UTC, jeddy3 commented on lib/rules/lightness-notation/README.md
> +```
```suggestion
```

2023-12-10 17:10 UTC, jeddy3 commented on lib/rules/lightness-notation/README.md
> +```
```suggestion
```

2023-12-12 01:41 UTC, ybiquitous approved these changes
Thanks, LGTM 👍🏼 

One more request, can you add a changelog entry via `npx changeset add`?
Ref https://github.com/stylelint/stylelint/blob/e28036e8c6121e2293a57986998af941ef2acc01/.changeset/early-jobs-hunt.md?plain=1

2023-12-12 03:21 UTC, Mouvedia commented on lib/rules/lightness-notation/__tests__/index.mjs
minor

Maybe add an example using `deg`.

2023-12-12 03:32 UTC, Mouvedia approved these changes
LGTM

There might be potential futur refactors seeing the similarities between the 2 rules.

2023-12-12 12:29 UTC, jeddy3 approved these changes
LGTM, thank you!

(The rule falls neatly into [the wish](https://github.com/stylelint/stylelint/issues/7396#issue-2035832595) of supporting modern CSS in the `16.x`)

2023-12-16 17:00 UTC, merged