Ignore multiline SCSS interpolation
stylelint/stylelint pull request #7406
Opened 2023-12-16 18:39 UTC by FloEdelmann

> Which issue, if any, is this issue related to?

Closes #7403.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2023-12-17 08:33 UTC, jeddy3 requested changes
Thank you.

I've requested a tweak to the changelog message, otherwise LGTM.

2023-12-17 08:33 UTC, jeddy3 commented on .changeset/new-bananas-sell.md
> +Fixed: Ignore multiline SCSS interpolation e.g. in `declaration-property-value-no-unknown`
```suggestion
Fixed: `declaration-property-value-no-unknown` and other false positives for multiline SCSS interpolation.
```

To follow our conventions.

2023-12-18 00:15 UTC, ybiquitous approved these changes
Thanks. LGTM 👍🏼

2023-12-18 08:43 UTC, jeddy3 approved these changes

2023-12-18 08:43 UTC, merged