fix: deduplicate `border-style` and `border-color`
stylelint/stylelint pull request #7546
Opened 2024-03-06 02:40 UTC by G-Rath

> Which issue, if any, is this issue related to?

Relates to #7506

> Is there anything in the PR that needs further explanation?

From what I can tell, I think it'll be a lot more work to support deduplicating `border-width` (because you can have multiple values, so it's only safe to interact when there's just one value) and with `border` (because you need to consider what options are already support).

I've done this in the meantime because it's safe and easy improvement to land straight away.

I've not added a changeset yet because it seems to want a GitHub Personal Token which doesn't seem right - if someone wants to handle that instead, be my guest :)

2024-03-07 00:16 UTC, ybiquitous requested changes
@G-Rath Thanks for the pull request. It's worth fixing these false negatives around the `border` shorthand.

But this fix doesn't make sense because the newly added `border` overwrites the existing `border` entry:

https://github.com/stylelint/stylelint/blob/74145ce67ae9c5afe8b61f6917ffd73dfc99c16c/lib/reference/properties.mjs#L45-L62

This case is tricky... 🤔

2024-03-07 00:19 UTC, G-Rath commented
> But this fix doesn't make sense because the newly added border overwrites the existing border entry:

I'm not sure what you mean - I've added a test that shows with this change the rule will now autocorrect code that it didn't before, which to me indicates its not being overwritten?

So to me this is at least an _improvement_ even though it doesn't resolve everything.

2024-03-07 00:29 UTC, ybiquitous commented
Please check out the failure on CI:

```
FAIL lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.mjs
  ● declaration-block-no-shorthand-property-overrides › reject › [ true ] › 'a { border-top-width: 1px; top: 0; bottom: 3px; border: 2px solid blue; }' › no description

    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []

      at Object.<anonymous> (node_modules/jest-preset-stylelint/getTestRule.js:81:29)
```

https://github.com/stylelint/stylelint/actions/runs/8166175436/job/22369564288?pr=7546#step:7:1379

2024-03-07 00:32 UTC, G-Rath commented
huh that's weird - I had that locally but fixed it before pushing:

```
Test Suites: 1 passed, 1 total
Tests:       81 passed, 81 total
Snapshots:   0 total
Time:        0.382 s, estimated 1 s
Ran all test suites matching /declaration-block-no-redundant-longhand-properties/i
```

2024-03-07 00:38 UTC, ybiquitous commented
According to the [CSS spec](https://drafts.csswg.org/css-backgrounds/#propdef-border), I think `longhandSubPropertiesOfShorthandProperties` should have the `border` entry as:

```js
	[
		'border',
		new Set([
			// prettier-ignore
			'border-width',
			'border-style',
			'border-color',
		]),
	],
```

If it makes sense, we have to fix the `declaration-block-no-redundant-longhand-properties` and `declaration-block-no-shorthand-property-overrides` logic, using the `border` properties.

2024-03-15 20:43 UTC, G-Rath commented
@ybiquitous unless I've missed something my expectation is that will be hard to support as that's only true if each long-hand property has only a single value which I'm not sure if the current implementation is already expecting; if its not, then there will need to be some way to express that in the configuration of `longhandSubPropertiesOfShorthandProperties`.

Digging a bit deeper, I think part of the issue is that the logic currently doesn't expect there to be multiple combinations of long-forms for the same properties, which I thought it did - and so right now its implemented to detect when someone has _all_ of the properties for setting color, width, and style for all four borders.

Unfortunately I think I'm going to have to put this down as it looks like improving this will require a decent refactor and I've not got enough experience with the codebase and related CSS to tackle that at this point.

2024-03-15 20:43 UTC, closed without merging