Fix declaration block no redundant longhand properties autofix font variant
stylelint/stylelint pull request #7734
Opened 2024-06-02 18:58 UTC by Bilie

> Which issue, if any, is this issue related to?

Closes https://github.com/stylelint/stylelint/issues/7620

> Is there anything in the PR that needs further explanation?

Hi, I have updated the properties file and added few tests, let me know if there is anything missing or can be improved

2024-06-03 09:01 UTC, ybiquitous requested changes
@Bilie Thanks for the pull request! Can you address my review comments?

---

[suggest] Can you remove the following `skip` in `declaration-block-no-shorthand-property-overrides` test cases? It should pass now.

https://github.com/stylelint/stylelint/blob/b5b3799cc107ede5b418bef6ef64bab072b2deab/lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.mjs#L211

2024-06-03 09:03 UTC, ybiquitous commented on lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
> +			message: messages.expected('font-variant'),
In addition, to test if a fixed code is in the correct order, can you replace only `foo` values with other values (e.g. `foo1`, `foo2`, etc.)?

2024-06-03 23:50 UTC, Mouvedia commented on lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
> +						font-variant: foo;
medium

Could you put real values?
When all values are `foo` the test cannot detect that the order is incorrect from the `fixed` string.
This is partly my fault.

2024-06-04 15:02 UTC, Bilie commented
Hi thank you both for the review, it has been really helpful! 😊 I think I have addressed all comments, but if I have missed anything, just let me know

2024-06-04 15:20 UTC, ybiquitous requested changes
@Bilie Thanks! Can you take a look at my additional comments, please? This PR seems overall good, though.

2024-06-04 15:20 UTC, ybiquitous commented on lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
> +				`,
[suggest] Can you keep indentation consistent with other test cases?

```suggestion
			code: stripIndent`
				a {
					font-variant: foo1 foo2 foo3 foo4 foo5 foo6 foo7;
				}
			`,
```

2024-06-04 15:20 UTC, ybiquitous commented on lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
> +				`,
[suggest] Let's keep indentation consistent.

```suggestion
			code: stripIndent`
				a {
					font-variant-ligatures: foo1;
					font-variant-position: foo2;
					font-variant-caps: foo3;
					font-variant-numeric: foo4;
					font-variant-alternates: foo5;
					font-variant-east-asian: foo6;
					font-variant-emoji: foo7;
				}
			`,
```

2024-06-04 15:20 UTC, ybiquitous commented on lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
> +			`,
[suggest] Let's reorder `fixed` and `message` like other cases:

```suggestion
			fixed: stripIndent`
				a {
					font-variant: foo1 foo2 foo3 foo4 foo5 foo6 foo7;
				}
			`,
			message: messages.expected('font-variant'),
```

2024-06-04 15:20 UTC, ybiquitous commented on lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
> +	config: [true, { ignoreShorthands: ['/^font-variant/'] }],
[suggest] `ignoreShorthands` has been tested already, so can you remove this case?

Ref https://github.com/stylelint/stylelint/pull/7734/files#diff-1f86a8d8167e5474d3acb984827780d6f4fdc4b66d36478c75280f22c7e2b3cbR976

2024-06-04 15:20 UTC, ybiquitous commented on lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.mjs
>  			endLine: 1,
[suggest] In addition, it'd be great if you could add `column`/`endColumn` like other cases 🙏🏼 

```suggestion
			line: 1,
			column: 36
			endLine: 1,
			endColumn: 48
```

2024-06-05 19:31 UTC, Mouvedia commented
off topic

It seems like there's a typo on https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant.
It should be `Specifies the keywords and functions related to the font-variant-ALTERNATES longhand property.`.

2024-06-06 09:05 UTC, ybiquitous approved these changes
Thank you. LGTM 👍🏼

2024-06-13 03:02 UTC, merged