Add `name` configuration property under `overrides`
stylelint/stylelint pull request #8095
Opened 2024-10-29 14:11 UTC by ryo-manba

> Which issue, if any, is this issue related to?

Closes #7854 

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2024-10-30 01:45 UTC, ybiquitous requested changes
@ryo-manba Thanks for the pull request. Can you make additional changes?

- Add a test case for the new property, which should break nothing.
- Document the property in our configuration guide.

2024-11-05 12:32 UTC, ybiquitous commented on docs/user-guide/configure.md
> +- may include a `name` property to provide a description of the override's purpose.
[suggestion] To keep consistency with the 2 lines above.

```suggestion
- may contain a `name` property to provide a description of the override's purpose.
```

2024-11-05 12:35 UTC, ybiquitous commented on docs/user-guide/configure.md
> +- may contain a `name` property to provide a description of the override's purpose.
Remove an extra period to keep consistent with the line above.

```suggestion
- may contain a `name` property to provide a description of the override's purpose
```

2024-11-07 10:57 UTC, Mouvedia approved these changes

2024-11-07 10:57 UTC, Mouvedia commented on lib/__tests__/overrides.test.mjs
> +		expect(linted.results[0].warnings[0].rule).toBe('block-no-empty');
```suggestion
		expect(linted.results[0].warnings[0].rule).toBe('block-no-empty');
		expect(linted.results[0].warnings[1].rule).toBe('color-named');
```

2024-11-07 10:59 UTC, Mouvedia commented on lib/__tests__/overrides.test.mjs
> +		expect(linted.results[0].warnings[0].rule).toBe('block-no-empty');
```suggestion
		expect(linted.results[0].warnings[0].rule).toBe('block-no-empty');
		expect(linted.results[0].warnings[1].rule).toBe('color-named');
```

2024-11-07 13:06 UTC, ybiquitous commented
Thank you for the additional review. I'll merge this. 😃

2024-11-07 13:08 UTC, merged