Add `messageArgs` to `selector-pseudo-element-colon-notation` and `media-feature-name-unit-allowed-list`
stylelint/stylelint pull request #8252
Opened 2024-12-30 00:21 UTC by Mouvedia

> Which issue, if any, is this issue related to?

#4117
followup of #8236 and #8239

> Is there anything in the PR that needs further explanation?

The consistency effort is starting to surface problems.
Once all the rules that pass `messageArgs` to `report` have their types updated, we way flow the types from `messages` to `message`.

i.e.
```ts
type CommonOptions = {
	severity: Severity;
	message: RuleMessage; // <<<
	url: string;
	reportDisables: boolean;
	disableFix: boolean;
}
```

ref https://stylelint.io/user-guide/configure/#message

One of the goals apart from consistency is to have autocompletion when using js/mjs/cjs configs.
Sadly we cannot achieve it through JSON schema.

2024-12-31 19:08 UTC, Mouvedia commented on types/stylelint/index.d.ts
> +			...args: [T] extends [never]
To avoid the distributive nature of TS conditional types we need a non-naked type parameter.
i.e. `T extends never` wouldn't work

2025-01-01 06:46 UTC, ybiquitous requested changes
Thanks for the pull request. For the support for `messageArgs`, LGTM. (as the PR title says)

However, I'm against mixing the `messageArgs` changes and polishing the types. If you want to discuss the types, you should separate a PR.

For the types, I'm worried that the types would be too complex to maintain. Do we really need such types?

2025-01-01 11:11 UTC, Mouvedia commented
> For the types, I'm worried that the types would be too complex to maintain. Do we really need such types?

Right now it's not completely warranted once I type the other half—which is around 50 more rules—it will be evident.

> …you should separate a PR.

I can but that part won't have a changeset anyway, it's just an enhancement.

2025-01-02 12:50 UTC, ybiquitous approved these changes
Thank you for simplifying this PR. LGTM 👍🏼 

Let's discuss the types on a follow-up PR.

2025-01-02 13:51 UTC, merged